blank_issues_enabled: false
contact_links:
  - name: cpomdp Documentation
    url: https://cpomdp.inferogenesis.com/
    about: Please check the full documentation and API reference before opening an issue.